common_files:
  bot_branch_name: broadcast-common-files-1
  topics_to_include: myqbertopic
  patterns_to_include: >
    .gitattributes, .editorconfig , README.md
  destination: .
  commit_message: |
    chore: update of common files
    Test string to add into PRs body
  repos_to_ignore: >
    qubership-core-build
obsoleted_files_cleanup:
  patterns_to_remove: .github/workflows/pr-assigner.yaml
  bot_branch_name: broadcast-remove-pr-assigner-yaml
  commit_message: |
    feat(ci): removed workflow-templates/pr-assigner.yaml.
